### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by lefnire** [ranm8/winston-newrelic#5]
App starts up with error:

``` shell
2015-01-03T00:34:44.244623+00:00 app[web.1]: TypeError: undefined is not a function
2015-01-03T00:34:44.244626+00:00 app[web.1]:     at Logger.add (/app/node_modules/winston/lib/winston/logger.js:435:41)
2015-01-03T00:34:44.244628+00:00 app[web.1]:     at Object.<anonymous> (/app/src/logging.js:27:16)
2015-01-03T00:34:44.244630+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2015-01-03T00:34:44.244633+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2015-01-03T00:34:44.244635+00:00 app[web.1]:     at Module.load (module.js:356:32)
2015-01-03T00:34:44.244637+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2015-01-03T00:34:44.244640+00:00 app[web.1]:     at Function.cls_wrapMethod [as _load] (/app/node_modules/newrelic/lib/shimmer.js:220:38)
2015-01-03T00:34:44.244642+00:00 app[web.1]:     at Module.require (module.js:364:17)
2015-01-03T00:34:44.244644+00:00 app[web.1]:     at require (module.js:380:17)
2015-01-03T00:34:44.244647+00:00 app[web.1]:     at Object.<anonymous> (/app/src/server.js:7:15)
2015-01-03T00:34:45.084529+00:00 app[web.1]: [nodemon] app crashed - waiting for file changes before starting...
```

https://github.com/mcku/winston-newrelic/commit/eff336f2de8edb400c33026a775913c4ba225b62 is supposed to have fixed the error, but no cigar. I've tried `"winston": "0.8.0",` _and_ `"winston": "~0.8.x",` (ie, pinning _and_ upgrading). xfref https://github.com/HabitRPG/habitrpg/issues/4471

**Comment by lefnire** [comment]
cc @mcku. Above fork continues to give the same error
